### ISSUE TITLE
OpenDefault (Linux).sublime-settings or OpenDefault.sublime-settings?

### ISSUE THREAD

**Issue by luxe** [SublimeText/OpenDefaultApplication#3]
The readme says to add `OpenDefault (Linux).sublime-settings` to `User/`.  
This did not work for me on a linux machine.  However, `OpenDefault.sublime-settings` does work.  Not sure if the "(Linux)" is a sublime thing or something to do with the code.

**Comment by FichteFoll** [comment]
You are right in that the readme (and the settings structure seen in this package) is wrong. Platform-specific settings only work for the global `Preferences.sublime-settings` file, not for plugin settings files.

Pull requests welcome.
